### ISSUE TITLE
Mongoid support

### ISSUE THREAD

**Issue by dks17** [lynndylanhurley/devise_token_auth#1198]
Hello.
I would like bring Mongoid gem support for the gem. Now the gem is not working with Mongoid as fact.

General plan is:
- [x] Replace fixtures by factorybot. Fixtures is not working with Mongoid. #1197 
- [x] Add DatabseCleaner gem. #1209 
- [x] Change the gem initialization. #1209 
- [x]  Add Mongoid document models for users. #1209 
- [x] Escape user id checking in conditionals. #1209 
- [x] Resolve `Overwriting existing field locked_at` warn (see [comment](https://github.com/lynndylanhurley/devise_token_auth/issues/1198#issuecomment-412331273)). Fixed in [#55](https://github.com/mongoid/mongoid-locker/pull/55) PR for `mongoid-locker` gem.
- [x] Add Mongoid user model generator. #1209 
- [x] Add documentation. #1209 

References:
- **Generator doesn't work correctly with mongoid and/or rails-api #14**
- **Mongoid Support #15**
- **NoMethodError (undefined method `[]=' for nil:NilClass) #178**
- **Getting `table_exists?' error when using devise_token_auth with Mongoid #325**
- **Support for Mongodb / Mongoid #373**
- **Add mongoid support #502**
- **Rails 5 + mongoid + devise_token_auth - undefined method `add_mongoid_support=' for DeviseTokenAuth:Module (NoMethodError) #675**
- **Signing in with Mongoid 6 + Rails 5 causes AuthenticationError #742**

**Comment by MaicolBen** [comment]
Check https://github.com/lynndylanhurley/devise_token_auth/issues/15, we might put a bounty on this issue

**Comment by dks17** [comment]
> Check #15, we might put a bounty on this issue

It is old issue. Now situation is more complicated then it was in 2014. I have encounted with many other issues including this.

The gem is hardcoded on ActiveRecord. And when the concern `DeviseTokenAuth::Concerns::User` is included in Mongoid model it influences nothing because of the gem is already initialized with ActtiveRecord.

**Comment by dks17** [comment]
`devise` use the same `:locked_at` field as `mongoid-locker`. They both use the same field for different purposes. [Allow customizing locked_at field (clash with Devise)](https://github.com/mongoid/mongoid-locker/issues/26)

```ruby
class LockableUser
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Locker

  # many fields here

  ## Lockable
  field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  field :locked_at,       type: Time

  # Include default devise modules.
  devise :database_authenticatable, :registerable, :lockable
  include DeviseTokenAuth::Concerns::User

  include Mongoid::Locker
end
```
When Mongoid::Locker is included there is warn in console
```console
WARN -- : Overwriting existing field locked_at in class LockableUser.
```
I have already pulled patch into `mongoid-locker` and hope it will be accepted ([Customizable :locked_at and :locked_until fields](https://github.com/mongoid/mongoid-locker/pull/55)). Or we should care about another solution for it.

**Comment by MaicolBen** [comment]
@dks17 I don't know the reason of the `BINARY`, maybe @lynndylanhurley knows. Try to avoid making a huge PR for mongo

**Comment by dks17** [comment]
@MaicolBen I have almost finished.

Should I add generator for `mongoid` user model and documentation in upcoming pr?

I should write description about changes. How should do it better?

- Should I add some UPGRADE.md file? (by default you must have devise config file or [specify ORM](https://github.com/plataformatec/devise/blob/3b0bc08ec67dd073ddd6d043c71646c2784ced6c/lib/generators/templates/devise.rb#L29))
- Should I put description in separate file i.e. MONGOID.md, about using the gem with `mongoid`.

**Comment by MaicolBen** [comment]
Why `UPGRADE.md` ? I would recommend adding a section mongo in https://github.com/lynndylanhurley/devise_token_auth/blob/master/SUMMARY.md and add the doc under docs

**Comment by dks17** [comment]
> Why UPGRADE.md ?

Upcoming changes may break initialization order of the gem. I just want users be informed about it. We discuss it when I pull changes. Hope for your help.
Thanks.

**Comment by dks17** [comment]
@MaicolBen need your help.
This two methods in `rescue` block are never fired. It looks like duplicate of functionality in `else` block which is above.

https://github.com/lynndylanhurley/devise_token_auth/blob/2413d0015fa137ccc87444c0b2dbfd73c5f131f5/app/controllers/devise_token_auth/registrations_controller.rb#L33-L68

This piece of code is not covered with tests.
https://github.com/lynndylanhurley/devise_token_auth/blob/2413d0015fa137ccc87444c0b2dbfd73c5f131f5/test/controllers/devise_token_auth/registrations_controller_test.rb#L377-L402

Value of `@data['errors']` in tests is:
```ruby
{"email"=>["has already been taken"],
 "full_messages"=>["Email has already been taken"]}
```
`response.status` is also `422`.

I need to avoid `ActiveRecord` constant in the code. What should I do with it? Can I remove this `rescue` block and `render_create_error_email_already_exists` method?

**Comment by MaicolBen** [comment]
@dks17  it makes sense, `save` without bang won't raise exceptions

**Comment by MaicolBen** [comment]
@dks17 is there any tasks missing for completing this support?

**Comment by dks17** [comment]
@MaicolBen It's completed. Thanks.

**Comment by dks17** [comment]
I got bounty for this. Thanks to the community.

**Comment by luzioluna** [comment]
Hello! So is devise_token_auth compatible with mongoid now? I am still only able to get it to run at all with the BunHouth/devise_token_auth.git', branch: 'mongoid' version but it is throwing the Unpermitted parameters: :format, :session errors.

**Comment by dks17** [comment]
@luzioluna hello.
It looks like you use some old fork of the repository.

Please, see **How do I use the gem with Mongoid?** #1263

**Comment by baranyeni** [comment]
Hey folks! Am I the only one who receives such error with this gem?

Gemfile:
gem 'devise_token_auth', git: 'https://github.com/BunHouth/devise_token_auth.git', branch: 'mongoid'

error:
Because every version of devise_token_auth depends on rails < 6
  and Gemfile depends on rails ~> 7.0.4.2,
  devise_token_auth cannot be used.
So, because Gemfile depends on devise_token_auth >= 0,
  version solving has failed.
